#!/usr/bin/env bash

alias ec-show-cmds='grep "^#--" $SRCTOP/ec/sandbox-env/bashrc.glip'
alias ecmongo='mongo --host $EC_MONGO_HOST --port $EC_MONGO_PORT'
alias ecredis='redis-cli -p $EC_REDIS_PORT -a $EC_REDIS_PASSWORD'
alias ecredisslave='redis-cli -p $EC_REDIS_SLAVE_PORT -a $EC_REDIS_PASSWORD'
alias ecstartapi='echo "ec API server launched on port $EC_API_PORT. Log is $EC_LOGTOP/ec-api.log";(cd $SRCTOP/ec && node bin/api_server.js >$EC_LOGTOP/ec-api.log 2>&1)&'
alias ecstartcache='echo "ec cache server launched on port $EC_CACHE_PORT. Log is $EC_LOGTOP/ec-cache.log";(cd $SRCTOP/ec && node bin/cache_server.js >$EC_LOGTOP/ec-cache.log 2>&1)&'
alias ecstartgrunt='echo "starting grunt"; (cd $SRCTOP/ec && grunt >>$EC_LOGTOP/grunt.log 2>&1)&'
alias ecstartguzzler='echo "starting guzzler"; (cd $SRCTOP/ec && node bin/guzzler.js >>$EC_LOGTOP/guzzler.log 2>&1)&'
alias ecstartmongo='echo "launching mongo on port $EC_MONGO_PORT"; mongod -f $DEVDATA/config/mongo.conf'
alias ecstartredis='echo "launching redis on port $EC_REDIS_PORT"; redis-server $DEVDATA/config/redis.conf'
alias ecstartredisslave='echo "launching redis slave on port $EC_REDIS_SLAVE_PORT"; redis-server $DEVDATA/config/redis-slave.conf'
alias ecstartsexio='echo "ec sexIO server launched on port $EC_SEXIO_PORT. Log is $EC_LOGTOP/ec-sexio.log";(cd $SRCTOP/ec && node bin/sexio.js >$EC_LOGTOP/ec-sexio.log 2>&1)&'
alias ecstatus='ps -e -o user:30=UID -o pid,ppid,pgid,c,stime,tty=TTY -o time,cmd -H|grep ^$USER|egrep -e "grunt|redis|mongo|node|elastic"|egrep -v -e "grep|tail|emacs|vim" && echo "SERVER URL: https://"$HOSTNAME":"$EC_SEXIO_PORT'
alias ecstopapi='p=$(get_node_service_pid api_server.js); echo "killing api at $p"; kill $p'
alias ecstopcache='p=$(get_node_service_pid cache_server.js); echo "killing cache at $p"; kill $p'
alias ecstopgrunt='p=$(get_grunt_pid); echo "killing grunt at $p"; kill $p'
alias ecstopguzzler='p=$(get_node_service_pid guzzler.js); echo "killing guzzler at $p"; kill $p'
alias ecstopmongo='kill `cat $DEVDATA/pids/mongod.pid`; /bin/rm $DEVDATA/pids/mongod.pid'
alias ecstopredis='kill `cat $DEVDATA/pids/redis.pid`'
alias ecstopredisslave='kill `cat $DEVDATA/pids/redis-slave.pid`'
alias ecstopsexio='p=$(get_node_service_pid sexio.js); echo "killing sexio at $p"; kill $p'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gitlog='git log --graph --oneline --all --decorate'
alias glo='git log --oneline'
alias grep='grep --color=auto'
alias l.='ls -d .* --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias myps='ps -ejHf'
alias vi='vim'
alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'